# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/curtine/git/daemon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/curtine/git/daemon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/curtine/git/daemon/CMakeFiles /home/curtine/git/daemon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/curtine/git/daemon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named restart

# Build rule for target.
restart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 restart
.PHONY : restart

# fast build rule for target.
restart/fast:
	$(MAKE) -f CMakeFiles/restart.dir/build.make CMakeFiles/restart.dir/build
.PHONY : restart/fast

#=============================================================================
# Target rules for targets named stop

# Build rule for target.
stop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stop
.PHONY : stop

# fast build rule for target.
stop/fast:
	$(MAKE) -f CMakeFiles/stop.dir/build.make CMakeFiles/stop.dir/build
.PHONY : stop/fast

#=============================================================================
# Target rules for targets named disable

# Build rule for target.
disable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disable
.PHONY : disable

# fast build rule for target.
disable/fast:
	$(MAKE) -f CMakeFiles/disable.dir/build.make CMakeFiles/disable.dir/build
.PHONY : disable/fast

#=============================================================================
# Target rules for targets named start

# Build rule for target.
start: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 start
.PHONY : start

# fast build rule for target.
start/fast:
	$(MAKE) -f CMakeFiles/start.dir/build.make CMakeFiles/start.dir/build
.PHONY : start/fast

#=============================================================================
# Target rules for targets named status

# Build rule for target.
status: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 status
.PHONY : status

# fast build rule for target.
status/fast:
	$(MAKE) -f CMakeFiles/status.dir/build.make CMakeFiles/status.dir/build
.PHONY : status/fast

#=============================================================================
# Target rules for targets named daemon

# Build rule for target.
daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemon
.PHONY : daemon

# fast build rule for target.
daemon/fast:
	$(MAKE) -f CMakeFiles/daemon.dir/build.make CMakeFiles/daemon.dir/build
.PHONY : daemon/fast

#=============================================================================
# Target rules for targets named enable

# Build rule for target.
enable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enable
.PHONY : enable

# fast build rule for target.
enable/fast:
	$(MAKE) -f CMakeFiles/enable.dir/build.make CMakeFiles/enable.dir/build
.PHONY : enable/fast

daemon.o: daemon.cpp.o

.PHONY : daemon.o

# target to build an object file
daemon.cpp.o:
	$(MAKE) -f CMakeFiles/daemon.dir/build.make CMakeFiles/daemon.dir/daemon.cpp.o
.PHONY : daemon.cpp.o

daemon.i: daemon.cpp.i

.PHONY : daemon.i

# target to preprocess a source file
daemon.cpp.i:
	$(MAKE) -f CMakeFiles/daemon.dir/build.make CMakeFiles/daemon.dir/daemon.cpp.i
.PHONY : daemon.cpp.i

daemon.s: daemon.cpp.s

.PHONY : daemon.s

# target to generate assembly for a file
daemon.cpp.s:
	$(MAKE) -f CMakeFiles/daemon.dir/build.make CMakeFiles/daemon.dir/daemon.cpp.s
.PHONY : daemon.cpp.s

disable.o: disable.cpp.o

.PHONY : disable.o

# target to build an object file
disable.cpp.o:
	$(MAKE) -f CMakeFiles/disable.dir/build.make CMakeFiles/disable.dir/disable.cpp.o
.PHONY : disable.cpp.o

disable.i: disable.cpp.i

.PHONY : disable.i

# target to preprocess a source file
disable.cpp.i:
	$(MAKE) -f CMakeFiles/disable.dir/build.make CMakeFiles/disable.dir/disable.cpp.i
.PHONY : disable.cpp.i

disable.s: disable.cpp.s

.PHONY : disable.s

# target to generate assembly for a file
disable.cpp.s:
	$(MAKE) -f CMakeFiles/disable.dir/build.make CMakeFiles/disable.dir/disable.cpp.s
.PHONY : disable.cpp.s

enable.o: enable.cpp.o

.PHONY : enable.o

# target to build an object file
enable.cpp.o:
	$(MAKE) -f CMakeFiles/enable.dir/build.make CMakeFiles/enable.dir/enable.cpp.o
.PHONY : enable.cpp.o

enable.i: enable.cpp.i

.PHONY : enable.i

# target to preprocess a source file
enable.cpp.i:
	$(MAKE) -f CMakeFiles/enable.dir/build.make CMakeFiles/enable.dir/enable.cpp.i
.PHONY : enable.cpp.i

enable.s: enable.cpp.s

.PHONY : enable.s

# target to generate assembly for a file
enable.cpp.s:
	$(MAKE) -f CMakeFiles/enable.dir/build.make CMakeFiles/enable.dir/enable.cpp.s
.PHONY : enable.cpp.s

restart.o: restart.cpp.o

.PHONY : restart.o

# target to build an object file
restart.cpp.o:
	$(MAKE) -f CMakeFiles/restart.dir/build.make CMakeFiles/restart.dir/restart.cpp.o
.PHONY : restart.cpp.o

restart.i: restart.cpp.i

.PHONY : restart.i

# target to preprocess a source file
restart.cpp.i:
	$(MAKE) -f CMakeFiles/restart.dir/build.make CMakeFiles/restart.dir/restart.cpp.i
.PHONY : restart.cpp.i

restart.s: restart.cpp.s

.PHONY : restart.s

# target to generate assembly for a file
restart.cpp.s:
	$(MAKE) -f CMakeFiles/restart.dir/build.make CMakeFiles/restart.dir/restart.cpp.s
.PHONY : restart.cpp.s

start.o: start.cpp.o

.PHONY : start.o

# target to build an object file
start.cpp.o:
	$(MAKE) -f CMakeFiles/start.dir/build.make CMakeFiles/start.dir/start.cpp.o
.PHONY : start.cpp.o

start.i: start.cpp.i

.PHONY : start.i

# target to preprocess a source file
start.cpp.i:
	$(MAKE) -f CMakeFiles/start.dir/build.make CMakeFiles/start.dir/start.cpp.i
.PHONY : start.cpp.i

start.s: start.cpp.s

.PHONY : start.s

# target to generate assembly for a file
start.cpp.s:
	$(MAKE) -f CMakeFiles/start.dir/build.make CMakeFiles/start.dir/start.cpp.s
.PHONY : start.cpp.s

status.o: status.cpp.o

.PHONY : status.o

# target to build an object file
status.cpp.o:
	$(MAKE) -f CMakeFiles/status.dir/build.make CMakeFiles/status.dir/status.cpp.o
.PHONY : status.cpp.o

status.i: status.cpp.i

.PHONY : status.i

# target to preprocess a source file
status.cpp.i:
	$(MAKE) -f CMakeFiles/status.dir/build.make CMakeFiles/status.dir/status.cpp.i
.PHONY : status.cpp.i

status.s: status.cpp.s

.PHONY : status.s

# target to generate assembly for a file
status.cpp.s:
	$(MAKE) -f CMakeFiles/status.dir/build.make CMakeFiles/status.dir/status.cpp.s
.PHONY : status.cpp.s

stop.o: stop.cpp.o

.PHONY : stop.o

# target to build an object file
stop.cpp.o:
	$(MAKE) -f CMakeFiles/stop.dir/build.make CMakeFiles/stop.dir/stop.cpp.o
.PHONY : stop.cpp.o

stop.i: stop.cpp.i

.PHONY : stop.i

# target to preprocess a source file
stop.cpp.i:
	$(MAKE) -f CMakeFiles/stop.dir/build.make CMakeFiles/stop.dir/stop.cpp.i
.PHONY : stop.cpp.i

stop.s: stop.cpp.s

.PHONY : stop.s

# target to generate assembly for a file
stop.cpp.s:
	$(MAKE) -f CMakeFiles/stop.dir/build.make CMakeFiles/stop.dir/stop.cpp.s
.PHONY : stop.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... restart"
	@echo "... install/local"
	@echo "... stop"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... disable"
	@echo "... start"
	@echo "... status"
	@echo "... daemon"
	@echo "... enable"
	@echo "... edit_cache"
	@echo "... daemon.o"
	@echo "... daemon.i"
	@echo "... daemon.s"
	@echo "... disable.o"
	@echo "... disable.i"
	@echo "... disable.s"
	@echo "... enable.o"
	@echo "... enable.i"
	@echo "... enable.s"
	@echo "... restart.o"
	@echo "... restart.i"
	@echo "... restart.s"
	@echo "... start.o"
	@echo "... start.i"
	@echo "... start.s"
	@echo "... status.o"
	@echo "... status.i"
	@echo "... status.s"
	@echo "... stop.o"
	@echo "... stop.i"
	@echo "... stop.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

